### ISSUE TITLE
Update Slack Link

### ISSUE THREAD

**Issue by harshitkumar31** [single-spa/single-spa.js.org#102]
**Describe the bug or question**
The slack invite link is no longer active. Can you update it?

**Comment by frehner** [comment]
Confirmed when using an incognito window

<img width="1431" alt="Screen Shot 2019-09-24 at 10 01 54 AM" src="https://user-images.githubusercontent.com/3054066/65528849-5c900c80-deb2-11e9-9f64-f5737208f2ee.png">

**Comment by internettrans** [comment]
I updated the link. Thanks for reporting this
