### ISSUE TITLE
Update the "Join the chat on Slack" link in README.md

### ISSUE THREAD

**Issue by randycox-eg** [single-spa/single-spa.js.org#110]
The Slack invitation link is no longer valid.

**Comment by internettrans** [comment]
Resolved in https://github.com/CanopyTax/single-spa.js.org/issues/110 and https://github.com/CanopyTax/single-spa-playground/pull/9

**Comment by tvvignesh** [comment]
@joeldenning You may want to update the same in the website footer URL as well.

**Comment by internettrans** [comment]
thanks - I just created https://github.com/CanopyTax/single-spa.js.org/pull/112 to address this. Also I linked to the wrong thing in my previous comment - here was my previous PR: https://github.com/CanopyTax/single-spa/pull/361
