### ISSUE TITLE
The doc's `Examples and starter kits` part not rightly redirect

### ISSUE THREAD

**Issue by dulinxi** [single-spa/single-spa.js.org#116]
**Describe the bug or question**
The doc's `Examples and starter kits` part not right redirect  [https://single-spa.js.org/docs/getting-started-overview](https://single-spa.js.org/docs/getting-started-overview)

**To Reproduce**
[https://single-spa.js.org/docs/getting-started-overview](https://single-spa.js.org/docs/getting-started-overview)

**Expected behavior**
It should be visit rightly

**Screenshots and/or console output**
If applicable, add screenshots or console output to help explain your problem.
![image](https://user-images.githubusercontent.com/12506382/68440693-d41dbf00-0206-11ea-8045-acf7395f266c.png)

**Additional context**
![image](https://user-images.githubusercontent.com/12506382/68440781-10511f80-0207-11ea-9a85-dbbb2e7ca1e8.png)

![image](https://user-images.githubusercontent.com/12506382/68441036-cfa5d600-0207-11ea-9c8a-1d8107961dc1.png)
The same error is happened when click these links

**Comment by filoxo** [comment]
Workaround for the time being: go directly to https://single-spa.js.org/ and click the 'Get Started' button which will take you to the API docs.

**Comment by gremlin896** [comment]
As this wasn't mentioned in the original issue I want to note that the same issue seems to happen for any path under docs/

Examples:
https://single-spa.js.org/docs/separating-applications
https://single-spa.js.org/docs/ecosystem-angular
https://single-spa.js.org/docs/starting-from-scratch

On the https://single-spa.js.org/docs/ page the 'Go to Tutorials' and 'Go to API Documentation' links also have the same behavior as the original issue

**Comment by frehner** [comment]
this should mostly be fixed now. big thanks to @lex111 for their work here
