### ISSUE TITLE
Yapi二次开发

### ISSUE THREAD

**Issue by cytgjf** [single-spa/single-spa.js.org#173]
你好，偶然间在Yapi二次开发的常见问题中发先你提出的：UnhandledPromiseRejectionWarning: Error: 初始化管理员账号 "admin@admin.com" 失败, E11000 duplicate key error collection: yapi.user index: email_1 dup key: { : "admin@admin.com" }这个问题，想请教下，这个是怎么解决的

**Comment by internettrans** [comment]
From Google translate:

> Hello, I accidentally posted your first question in the common problem of the secondary development of Yapi: UnhandledPromiseRejectionWarning: Error: failed to initialize the administrator account "admin@admin.com", E11000 duplicate key error collection: yapi.user index: email_1 dup key: {: "admin@admin.com"} This question, I would like to ask, how is this solved

To me, this does not sound like an error related to single-spa at all. It sounds like a problem with https://github.com/YMFE/yapi. I am closing this issue - but if I am mistaken, feel free to reopen / comment further.
