### ISSUE TITLE
Replace curly brackets with HTML representation

### ISSUE THREAD

**Issue by mstrlaw** [single-spa/single-spa.js.org#193]
Under api.md, Docusaurus doesn't render the curly brackets for:

`<dt>customProps?: Object = {}</dt>`

The HTML equivalent must be used, such as:

`<dt>customProps?: Object = &#123;&#125;</dt>`

**Comment by frehner** [comment]
thanks for the report. Do you mind making a PR to fix this? hopefully it's easy -- at the bottom of each page there is a `Edit this page` link that should take you directly to the `.md` file on github.
