### ISSUE TITLE
change example link

### ISSUE THREAD

**Issue by frehner** [single-spa/single-spa.js.org#194]
I thought we had removed the link on the homepage that goes to the old, deprecated surge.sh site.

In any case, I think it's time to replace it. potentially with one of the new repos that was created.

thoughts?

**Comment by internettrans** [comment]
I thought we had too - yes let's remove it.

**Comment by frehner** [comment]
you have a preference if it points to the react or the vue one?

**Comment by internettrans** [comment]
Hmm I don’t care maybe Vue
