### ISSUE TITLE
Add version to dependencies?

### ISSUE THREAD

**Issue by icaroponce** [single-spa/single-spa.js.org#20]
Hello there, 

I'm exploring this module and following the guide "Starting from scratch" I'm having many problems mainly regarding to babel and other dependencies versions. 

Ex: 

```
error css-loader@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".
error Found incompatible module
```

`Error: Cannot find module '@babel/core'`

After solving the ones above  (Which are quite simple to solve)

`Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/x/spa-test/node_modules/babel-preset-react/lib/index.js`

The last one I couldn't solve yet. Maybe you could provide the latest tested versions as suggested in the docs? I know it's not a problem of the `single-spa`, but I believe that making the docs/tutorials less prone to errors and tutorials might help the newcomers, hence bring more of them and maybe some future contributors. 

Just a suggestion.

Thanks for the good work.

**Comment by icaroponce** [comment]
**UPDATE**: After setting some older versions to the deps and removing the `mode` property from the webpack config, which is being pointed as invlaid, I made it compile successfully for the first time :D

**Comment by frehner** [comment]
sorry to hear about the issues that you've had! We probably should go through the docs again from a clean slate and make sure that everything is still working / up to date. 

Glad you got it to work though.

**Comment by icaroponce** [comment]
No problem. Thanks!
