### ISSUE TITLE
(docs) Broken links in documentation page

### ISSUE THREAD

**Issue by codesandtags** [single-spa/single-spa.js.org#221]
Hi everyone!

**Actual behavior**

I was reading the documentation but the next links are broken:

https://single-spa.js.org/docs/getting-started-overview/migrating-angularJS-tutorial.md
https://single-spa.js.org/docs/getting-started-overview/migrating-react-tutorial.md

**Expected behavior**

Allow to read the links in the documentation.

**Additional notes**

If I found any other links I will update this issue.

Cheers!

**Comment by internettrans** [comment]
Thanks for reporting this - I just transferred it to the single-spa.js.org repo. We'll hopefully fix it soon
