### ISSUE TITLE
Fix side navigation on single-spa-angular page

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa.js.org#230]
Something about the styling of the single-spa-angular page is causing the floating side navigation to be pushed to the bottom of the page. 

![Screen Shot 2020-04-16 at 11 43 59 AM](https://user-images.githubusercontent.com/4202993/79488863-a3249000-7fd7-11ea-87b7-805d6e7b1c6d.png)

**Comment by filoxo** [comment]
This only appears to be happening when the window is between 997px and 1291px.

**Comment by maximillianfx** [comment]
Hey! I'm looking for my first contribution. Can I take this?

**Comment by filoxo** [comment]
Sounds great! Feel free to post questions here or in the [single-spa Slack workspace](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ). Looking forward to your contribution!

**Comment by maximillianfx** [comment]
Thanks! So, looking the behavior in the page, if the page width is less then 1291px, the floating needs be removed from the screen? Or need be moved to another location in the page?

**Comment by filoxo** [comment]
Ideally the right nav should stay visible until the breakpoint at which left side nav is collapsed into a button.

**Comment by maximillianfx** [comment]
I found the problem and a (weird) solution, changing the column (article section) width with the class `col--9`, made the floating appear until the limit width of 997px. But I can't figure it out how to add this class on this section. Can you help me?

![fix](https://user-images.githubusercontent.com/7096390/88739347-ba176a00-d110-11ea-9c8f-ca2621ab1818.png)

**Comment by maximillianfx** [comment]
Hey! I found this issue in the Ember Section to. But, looking into React and Angular pages, the structure is the same, 
I haven't found a solution yet.

![Captura de Tela 2020-07-29 às 21 08 22](https://user-images.githubusercontent.com/7096390/88936222-0e2d6600-d259-11ea-87ac-869fe26f196d.png)
![Captura de Tela 2020-07-29 às 21 08 42](https://user-images.githubusercontent.com/7096390/88936231-12f21a00-d259-11ea-8f0c-c22953ae2f4b.png)

**Comment by filoxo** [comment]
Sorry about the lack of response! I think if possible, the ideal way to fix this is to find a good css selector (something with just the right specificity) and put that in our custom styles. Here are the docs on custom styles: https://docusaurus.io/docs/en/api-pages#styles

**Comment by maximillianfx** [comment]
Hi @filoxo , I made this change and the page is now showing the correct behavior, and other pages were not affected in my tests. Can you review this change? If this is right, I will proceed with the PR 😄

**Comment by filoxo** [comment]
That selector captures other `.col`s as well, so it is slightly too specific. In the below image it shows that it is applying the width to the container of the sidebar, which seems incorrect though it doesn't visually cause issues.

![Screen Shot 2020-07-30 at 1 31 55 PM](https://user-images.githubusercontent.com/4202993/88966158-1beae780-d269-11ea-8e8f-d750b14225ec.png)

What do you think of `main .row > [class="col"]` instead? This would target the `main` element which is where the primary content is, and just the element that has only "col" as the class. That is less specific and no longer matches the sidebar container.

As a side note, adding `.col--9` to that same element would also fix this but that would have to be done upstream at Docusaurus' repo, on [this component](https://github.com/facebook/docusaurus/blob/15e73daae757c5744568cc5d95c83dcd5885a6cd/packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx#L110-L112). The only reason I didn't suggest that before is because I don't think we would want to wait long to get this fix in, especially if its this simple.

**Comment by maximillianfx** [comment]
Yeah, I think that this solution is really better. I will make this change and retest 😄

**Comment by maximillianfx** [comment]
Here, this sounds great 😄 

![Captura de Tela 2020-07-30 às 17 37 50](https://user-images.githubusercontent.com/7096390/88972438-ec99a200-d28b-11ea-95ee-93da214dfed4.png)
![Captura de Tela 2020-07-30 às 17 38 04](https://user-images.githubusercontent.com/7096390/88972487-033ff900-d28c-11ea-9737-bbdae46e42df.png)

**Comment by filoxo** [comment]
Awesome! I appreciate that you tested and validated it again. Ready for a PR?

**Comment by maximillianfx** [comment]
Sure!  😄  🚀  🎉

**Comment by filoxo** [comment]
Resolved in #303. Thanks @maximillianfx!
