### ISSUE TITLE
Building spa-applications link does not exists

### ISSUE THREAD

**Issue by urko-b** [single-spa/single-spa.js.org#255]
In this part of single-spa website [documentation,](https://single-spa.js.org/docs/building-applications/) In this paragraph there is a link to  [register the application with single-spa](https://single-spa.js.org/docs/building-applications/configuration#registering-applications) 

![image](https://user-images.githubusercontent.com/11888892/81841485-d14fae00-954a-11ea-93bd-496602d6bf1c.png)

This link does not exists

![image](https://user-images.githubusercontent.com/11888892/81841397-a9f8e100-954a-11ea-9fe6-d6a1d978ea0f.png)

**Comment by internettrans** [comment]
Thanks for the bug report - yes we should fix this. I'll put together a PR

**Comment by urko-b** [comment]
Thanks to you for your content. If I would have known which url is the correct I would have made the PR.

**Comment by internettrans** [comment]
Wrong URL:
https://single-spa.js.org/docs/building-applications/configuration/#registering-applications

Correct URL:
https://single-spa.js.org/docs/configuration/#registering-applications

**Comment by internettrans** [comment]
Here's the pull request - https://github.com/single-spa/single-spa.js.org/pull/257
