### ISSUE TITLE
cannot close alies header

### ISSUE THREAD

**Issue by BartJanvanAssen** [single-spa/single-spa.js.org#263]
No disrespect, though we cannot reach the navigation on desktop. because this banner is on top of all items: 
![image](https://user-images.githubusercontent.com/4742816/83438461-c305fb00-a441-11ea-814d-672ed05d14ca.png)

**Comment by frehner** [comment]
>we cannot reach the navigation on desktop.

do you have an `X` on the right side of the banner? If not, can you please give us browser info to better debug? Thanks.

**Comment by frehner** [comment]
To be fair, the contrast on that button is kind of bad too

**Comment by BartJanvanAssen** [comment]
Have no X at all :(, a suggestion is to add little CSS to fix it to the bottom:

    position: fixed;
    bottom: 0;
    top: auto;

Is that something you would accept as a pr?

**Comment by BartJanvanAssen** [comment]
I see you checked in with the author, thanks!

**Comment by frehner** [comment]
Thanks for submitting, and let us or the author know if you have more issues

**Comment by blittle** [comment]
@BartJanvanAssen this is resolved.
