### ISSUE TITLE
"example root config" link leads to empty page

### ISSUE THREAD

**Issue by maxsbelt** [single-spa/single-spa.js.org#291]
I read "Configuring single-spa" documentation page:
https://single-spa.js.org/docs/configuration/#registering-applications

And found link that leads to empty page:
|link|empty page|
|---|---|
|<img width="889" alt="empty page" src="https://user-images.githubusercontent.com/950216/86328912-2310dc80-bc4e-11ea-8f13-3be79941c8e8.png">|<img width="1272" alt="Screenshot 2020-07-02 at 10 24 38" src="https://user-images.githubusercontent.com/950216/86329014-420f6e80-bc4e-11ea-9a11-142f727a4fdd.png">|

Seems like this link is used in multiple pages:
<img width="50%" alt="multiple pages" src="https://user-images.githubusercontent.com/950216/86328960-3328bc00-bc4e-11ea-9f8d-87d3f2c567a5.png">

Should it be updated?

**Comment by internettrans** [comment]
Thanks for the clear bug report - I'll submit a fix.
