### ISSUE TITLE
Trailing slash breaks links

### ISSUE THREAD

**Issue by philtim** [single-spa/single-spa.js.org#297]
**Steps to reproduce**
1. Visit this URL https://single-spa.js.org/docs/module-types
2. Click on any link, e.g. recommendations
3. Click on the browsers back button
4. Click again on the recommendations link

**Expected behavior**
No matter how often I navigate back and forth, the link for recommendations should always result in http://localhost:3000/docs/recommended-setup/#applications-versus-parcels-versus-utility-modules.md

**Current behavior**
When navigating back and forth, the link for recommendations (as well as any other link) looks like this: https://single-spa.js.org/docs/module-types/recommended-setup/#applications-versus-parcels-versus-utility-modules.md (module-types is still part of the URL, thus leading into a 404).

Upon further investigation, one can see that a redirect happens when a user navigates back. The URL looked like this https://single-spa.js.org/docs/module-types and after navigating back and forth and getting a redirect the URL looks like this https://single-spa.js.org/docs/module-types/ (notice the trailing slash). This only happens on the deployed version.

**Comment by internettrans** [comment]
See related #178. This was related to relative paths behaving different when there is trailing slash

**Comment by internettrans** [comment]
I have confirmed this is fixed after #299. Thanks for reporting this and submitting the first fix. Docusaurus v2 + Github pages is quite painful :'(
