### ISSUE TITLE
Update "Getting started" with create-single-spa

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa.js.org#335]
The ["Getting Started"](https://single-spa.js.org/docs/getting-started-overview) page should have a section that guides a user to:

1. create a root config
2. create a basic application (generic? or perhaps starting with single-spa-html?)
3. wiring up that application to the root-config

single-spa-playground kind of serves this purpose but I've helped a few people who do not understand what to do once their application is running there. 

Opening this discussion here to get feedback on whether this should be a beginner-to-single-spa's starting point.

**Comment by internettrans** [comment]
I agree that this would be a lot better than the current page.
