### ISSUE TITLE
single-spa-vue: Add `handleInstance` documentation

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa.js.org#344]
https://github.com/single-spa/single-spa-vue/pull/59 adds `handleInstance` api to support how Vue 3 registers plugins, and should be documented.

**Comment by internettrans** [comment]
Ah thanks for capturing this - I had forgotten about this but will document it now.

**Comment by internettrans** [comment]
This was already implemented in https://github.com/single-spa/single-spa.js.org/pull/337.
