### ISSUE TITLE
migrate existing spa css configuration link leads to 404

### ISSUE THREAD

**Issue by Lelith** [single-spa/single-spa.js.org#358]
In the following section: 
https://single-spa.js.org/docs/migrating-existing-spas/#2-getting-the-css-fonts-script-dependencies-to-work

this link https://single-spa.js.org/docs/migrating-existing-spas/configuration leads to a page not found error.

**Comment by internettrans** [comment]
Thanks for the bug report, this was fixed in https://github.com/single-spa/single-spa.js.org/pull/359
