### ISSUE TITLE
Docs: Vue ecosystem rending a parcel code example

### ISSUE THREAD

**Issue by JakeMetz8** [single-spa/single-spa.js.org#402]
**Describe the bug or question**
The code example for rendering a parcel in Vue [rendering a parcel](https://single-spa.js.org/docs/ecosystem-vue#rendering-a-parcel) seems to declare a variable **Widget** without assigning any value. 

Assuming this is in error?

**Comment by internettrans** [comment]
I've created https://github.com/single-spa/single-spa.js.org/pull/404 which fixes this.
