### ISSUE TITLE
Import maps - outdated info in docs

### ISSUE THREAD

**Issue by Mikilll94** [single-spa/single-spa.js.org#423]
**Describe the bug or question**
This docs page contains outdated information:
https://single-spa.js.org/docs/recommended-setup#import-maps

![Screenshot 2021-03-11 at 18 47 39](https://user-images.githubusercontent.com/17653648/110831161-43437180-829a-11eb-9dcd-a4d16b3f921c.png)

Currently **import maps** are fully supported in Chrome and Microsoft Edge. You can check this here:
https://caniuse.com/import-maps

**Expected behavior**
Docs should not contain outdated information

**Comment by frehner** [comment]
as of Feb 2020 (when that was written), that was correct.

PRs to update that line welcome. it's this file here https://github.com/single-spa/single-spa.js.org/blob/350c1b0a6e5e88c80a555f0cf13dbe82d8ee88da/website/versioned_docs/version-5.x/recommended-setup.md

**Comment by filoxo** [comment]
Whoever adds this information should include that [import map support landed in Chrome 89.](https://twitter.com/domenic/status/1366920609922506752?s=20)
